# Apache Drill v1.9.0 - embedded mode
#
# VERSION 0.1 - not for production, use at own risk
# General instructions: https://drill.apache.org/docs/install-drill-introduction/
#


#
# Using CentOS as the base image
#
FROM andypern/apache-drill-docker:v3

MAINTAINER andypern@gmail.com

ADD core-site.xml /opt/drill/apache-drill-1.9.0/conf/core-site.xml
